apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  default.conf.template: |
    server {
        location / {
            return 200 'Hello $MY_ENV';
            add_header Content-Type text/plain;
        }
    }