rootUser: minioadmin
rootPassword: minioadmin

mode: standalone

persistence:
  enabled: true
  storageClass: local-ssd
  size: 50Gi

service:
  type: NodePort
  nodePort: 30900

consoleService:
  type: NodePort
  nodePort: 30901
