apiVersion: v1
kind: Pod
metadata:
  name: storage-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: ssd-volume
  volumes:
    - name: ssd-volume
      persistentVolumeClaim:
        claimName: ssd-pvc
